export const CREATE_ADBANNER_REQUEST = "CREATE_ADBANNER_REQUEST";
export const CREATE_ADBANNER_SUCCESS = "CREATE_ADBANNER_SUCCESS";
export const CREATE_ADBANNER_FAIL = "CREATE_ADBANNER_FAIL"; 
export const CREATE_ADBANNER_RESET = "CREATE_ADBANNER_RESET"; 

export const GET_BANNERS_REQUEST = "GET_BANNERS_REQUEST";
export const GET_BANNERS_SUCCESS = "GET_BANNERS_SUCCESS";
export const GET_BANNERS_FAIL = "GET_BANNERS_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS"
